server:
  port: 6192
spring:
  application:
    name: fegin-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/